#include <Windows.h>
#include <stdio.h>

#define IOCTL_REPLACE_TOKEN CTL_CODE(FILE_DEVICE_UNKNOWN, 0x921, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_KILL_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x922, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_UNPROTECT_LSA CTL_CODE(FILE_DEVICE_UNKNOWN, 0x923, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)



#define DEVICE L"\\Device\\internalsRaccoon"
#define LINK L"\\DosDevices\\internalsRaccoon"

typedef struct {

	DWORD32 target;
	DWORD32 stealFrom;
	DWORD64 offset;

} TASK_INFO, * PTASK_INFO;
